#!/bin/bash

# Menerima sebuah string waktu dengan format Badak dan mengembalikan bentuk standar
# Format BADAK        : '%a %d %b %Y %r WIB'
# Contoh Format BADAK : 'Mon 08 Jun 2020 11:10:56 AM WIB'

# Output waktu dalam bentuk standar
# Format standar	  	: '$y$m$d-$H$M$S'
# Format standar contoh : '200608-111056'
# Input format selain BADAK = Unknown behaviour
function format_badak_to_str() {
	echo $(date -d $1 "+%y%m%d-%H%M%S");
}

# Menerima waktu dalam bentuk standar dan mengembalikan integer
# Output jumlah sekon yang telah terjadi semenjak epoch
function str_to_date() {
	initStr=$1;
	y=$(echo $initStr | cut -c 1-2);
	m=$(echo $initStr | cut -c 3-4);
	d=$(echo $initStr | cut -c 5-6);

	H=$(echo $initStr | cut -c 8-9);
	M=$(echo $initStr | cut -c 10-11);
	S=$(echo $initStr | cut -c 12-13);

	echo $(date -d "$y-$m-$d $H:$M:$S" +%s);
}

# Membandingkan dua buah string dengan format standar
# Jika waktu string pertama terjadi setelah waktu string kedua, output "SEQOK"
# Otherwise, output "SEQNO"
function is_a_after_b() {
	a=$(str_to_date $1);
	b=$(str_to_date $2);

	if [ $a -ge $b ]; then
		echo "SEQOK";
	else
		echo "SEQNO";
	fi
}

# This is the main script
# $1 = Script location to be checked

USER=$(cat $1 | head -4 | tail -1);

HEADER=$(cat $1 | head -1);

TMP=$(echo $HEADER | cut -c 19-);
START_TIME=$(format_badak_to_str $TMP);
LAST=$START_TIME;

echo "IgoRamli ZCZCSCRIPTSTART $START_TIME $USER";

# Dapatkan semua baris yang dienkoding sha1sum
lines=($(awk '/......-......-....-.*>/ {print $1}' $1));

# Cek tiap baris
for i in "${lines[@]}"
do
	:
	# Check timestamp is sequential
	TIMESTAMP=$(echo $i | cut -c 1-13);
	SEQ=$(is_a_after_b $TIMESTAMP $LAST);
	LAST=$TIMESTAMP

	# Check SHA1SUM is good
	WD=$(echo $i | cut -c 20- | sed 's/\/>//');
	GIVEN_SHA=$(echo $i | cut -c 15-18);
	REAL_SHA=$(echo "$TIMESTAMP-$USER-$WD"|sha1sum);
	if [ $(echo $REAL_SHA | cut -c 1-4) == $GIVEN_SHA ]
	then
		SUM="SUMOK";
	else
		SUM="SUMNO";
	fi

	echo "IgoRamli $USER $i $TIMESTAMP $SEQ $SUM $(echo $REAL_SHA | cut -c 1-8)";
done

FOOTER=$(cat $1 | tail -1);

TMP=$(echo $FOOTER | cut -c 16-);
END_TIME=$(format_badak_to_str $TMP);
SEQ=$(is_a_after_b $END_TIME $LAST);

echo "IgoRamli ZCZCSCRIPTSTOP $END_TIME $SEQ"